name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Latest Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    
    - name: Install 7zip
      run: choco install 7zip -y
    
    - name: Extract Ngrok using 7zip
      run: 7z x ngrok.zip -o"./ngrok"
    
    - name: Set Up Ngrok Configuration File
      run: |
        echo "version: 3" > ngrok.yml
        echo "authtoken: $2nvqTPIGWUgWzQ2AfzIxjb57hlq_49accnteDvzrPRGCUfMtG" >> ngrok.yml
        echo "tunnels:" >> ngrok.yml
        echo "  your_tunnel_name:" >> ngrok.yml
        echo "    proto: tcp" >> ngrok.yml
        echo "    addr: 3389" >> ngrok.yml
    
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    
    - name: Set User Password
      run: |
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password
    
    - name: Create Ngrok Tunnel
      run: .\ngrok\ngrok.exe start --config ngrok.yml your_tunnel_name
